---
- name: get pip installation file
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=~/ validate_certs=no

# for some reason sudo: yes and sudo_user: {{ ansible_ssh_user }} doesn't work :(
- name: install pip
  shell: sudo python ~/get-pip.py

- name: install python modules
  sudo: yes
  action: shell pip install virtualenv tox virtualenvwrapper

- name: install packages                                                       
  sudo: yes                                                                    
  apt: pkg={{ item }} state=latest update_cache=yes                              
  with_items:                                                                  
    - nodejs-legacy
    - npm
    - python-dev                                                               
    - ipython                                                                  
    - libz-dev                                                                 
    - fontconfig                                                               

- name: clean up apt stuff
  sudo: yes
  action: shell apt-get -f install && apt-get autoremove && apt-get -y autoclean && apt-get -y clean
  tags: clean
