# vim:ft=yaml
---
- name: Set bash as default shell
  shell: chsh -s /bin/bash

- name: ensure bashrc exists
  file: path=~/.bashrc state=touch

- name: setup bashrc file
  copy: src=.bashrc dest=~/.bashrc owner={{ ansible_ssh_user }}
        force=yes

- name: source bashrc
  shell: . ~/.bashrc

