---                                                                                
- hosts: local
  roles:                                                                           
    - common
    - devcommon
    - localdev
