---                                                                                
- hosts: local
  roles:                                                                           
    - common
    - common-dev
    - python-dev
