---                                                                                
- hosts: remote
  roles:
    - common
    - dev
    - { role: remote, default_user: jmeridth, default_group: admin, default_ssh_port: 22 }
