# vim:ft=yaml
---
- include: homebrew.yml
  when: ansible_os_family == 'Darwin'

- include: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: setup files                                                            
  copy: src={{ item.name }} dest=~/{{ item.name }} owner={{ ansible_user }} force=yes
  with_items:                                                                  
    - { name: '.zshrc' }                                                      
    - { name: '.jmaliases' }                                                      

- name: Set zsh as default shell
  shell: chsh -s {{ zsh_path }}
