---                      
- include: packages.yaml                                                          
  tags: packages

- include: git.yaml
  tags: git

- include: filesystem.yaml
  tags: filesystem

- include: bashrc.yaml 
  tags: bashrc

- include: vim.yaml
  tags: vim

- name: check if desktop
  shell: echo $XDG_CURRENT_DESKTOP
  register: is_desktop
  tags: desktop

- include: desktop.yaml
  when: is_desktop.stdout != ''
  tags: desktop
