---
- name: install homebrew formulas
  homebrew: name={{ item.name }} install_options={{ item.args }} state=present update_homebrew=yes
  with_items:
    - { name: pow, args:  }
    - { name: cmake, args: }
    - { name: watch, args: }
    - { name: coreutils, args: }
    - { name: python, args: }
    - { name: macvim, args: with-python, with-override-system-vim }
    - { name: caskroom/cask/brew-cask, args: }
    - { name: dynamodb-local, args: }
    - { name: imagemagick, args: }
    - { name: tree, args: }

- name: install homebrew casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - slack
    - launchrocket
    - google-chrome
    - appzapper
    - dropbox
    - skype
    - seil
    - firefox

- name: link apps
  shell: brew link {{ item }}
  with_items:
    - macvim
    - python
