# vim:ft=yaml
---

- name: get powerline fonts repo                                                           
  git: repo=git://github.com/powerline/fonts
       dest={{ default_dev_path }}/fonts accept_hostkey=True

- name: install fonts
  shell: "{{ default_dev_path }}/fonts/install.sh"
