---
- name: setup sshd_config
  sudo: yes
  template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config
    backup=yes
    # want to use validate='/usr/sbin/sshd -T -f %s' if possible
  notify:
  - restart sshd
