---
- name: install packages                                                       
  become: yes                                                                    
  apt: pkg={{ item }} state=latest update_cache=yes                              
  with_items:                                                                  
    - nodejs
    - nodejs-legacy
    - npm

- name: install keybase
  become: yes
  shell: sudo npm install -g keybase-installer && sudo keybase-installer
