---
- name: setup directories                                                      
  file: path=~/{{ item.path }} owner={{ ansible_user_id }} mode=0755 state=directory
  with_items:                                                                  
    - { path: '.vim' }                                                         
    - { path: '.vim/colors' }                                                  
    - { path: '.vim/bundle' }                                                  

- name: setup default colors
  copy: src='colors/' dest=~/.vim/colors/ owner={{ ansible_user_id }}
        force=yes
                                                                               
- name: setup files                                                            
  copy: src={{ item.name }} dest=~/{{ item.name }} owner={{ ansible_user_id }} force=yes
  with_items:                                                                  
    - { name: '.vimrc' }                                                      

- name: get Vundle repository                                                  
  git: repo=https://github.com/gmarik/Vundle.vim.git                           
       dest=~/.vim/bundle/Vundle.vim                                           
                                                                               
- name: run Vundle                                                             
  action: shell vim +PluginInstall! +qall
                                                                               
- name: overwrite colors
  file: path=~/.vim/colors/ state=absent
  tags: vimcolors

# this is much faster than a copy
- name: setup .weechat directory
  synchronize: src=~/.vim/bundle/vim-colorschemes/colors dest=~/.vim/

# this can take a bit
# ignoring errors in case it runs out of memory to complete (happens on AWS tiny instances)
# aka "virtual memory exhausted: Cannot allocate memory"
# maybe check if there is a swap and only install if there is one >= 1GB
- name: finish YouCompleteMe compilation
  sudo: yes
  shell: ./install.py --clang-completer
  args:
    chdir: ~/.vim/bundle/YouCompleteMe
  ignore_errors: yes

- name: get powerline fonts repo                                                           
  git: repo=git://github.com/powerline/fonts
       dest={{ default_dev_path }}/fonts accept_hostkey=True
  tags: powerlinefonts

- name: install fonts
  shell: "{{ default_dev_path }}/fonts/install.sh"
  tags: powerlinefonts
