---
- name: setup directories
  file: path=~/{{ item.path }} owner={{ ansible_user }} mode=0755 state=directory
  with_items:
    - { path: '.vim' }
    - { path: '.vim/colors' }
    - { path: '.vim/bundle' }

- name: setup default colors
  copy: src='colors/' dest=~/.vim/colors/ owner={{ ansible_user }}
        force=yes

- name: setup files
  copy: src={{ item.name }} dest=~/{{ item.name }} owner={{ ansible_user }} force=yes
  with_items:
    - { name: '.vimrc' }

- name: overwrite colors
  file: path=~/.vim/colors/ state=absent
  tags: vimcolors

# this is much faster than a copy
- name: setup .weechat directory
  synchronize: src=~/.vim/bundle/vim-colorschemes/colors dest=~/.vim/

- include: homebrew.yml
  when: ansible_os_family == 'Darwin'

- name: get powerline fonts repo
  git: repo=git://github.com/powerline/fonts
       dest={{ default_code_path }}/fonts accept_hostkey=True
  tags: powerlinefonts

- name: install fonts
  shell: "{{ default_code_path }}/fonts/install.sh"
  tags: powerlinefonts
