---
- name: get pip installation file
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=~/ validate_certs=no

# for some reason sudo: yes and sudo_user: {{ ansible_ssh_user }} doesn't work :(
- name: install pip
  shell: sudo python ~/get-pip.py

- name: install python modules
  sudo: yes
  action: shell pip install virtualenv tox virtualenvwrapper

- name: add docker key to local keychain
  sudo: yes                                                                    
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present

- name: add docker repository to apt sources
  sudo: yes
  shell: curl -s https://get.docker.io/ubuntu/ | sudo sh

- name: install packages                                                       
  sudo: yes                                                                    
  apt: pkg={{ item }} state=latest update_cache=yes                              
  with_items:                                                                  
    - python-software-properties                                               
    - python-dev                                                               
    - ipython                                                                  
    - libxml2-dev                                                              
    - libxslt1-dev                                                             
    - libz-dev                                                                 
    - fontconfig                                                               
    - libffi-dev
